# Change 'comments' to true for Disqus comments
disqus:
  comments: false
  disqus_shortname: 'millennial-3'
# If you are not using Google Analytics, please change 'google-ID' to an empty string
google-ID: 'UA-112060364-2'
menu:
- {name: 'Projects', url: '#projects'}
- {name: 'About Me', url: '#about'}
- {name: 'Contact', url: '#contact'}
# Available social icons are powered by Font Awesome, so you can use any icon that they offer
social:
- {icon: 'linkedin', link: 'https://www.linkedin.com/in/akshatnagar02/'}
- {icon: 'envelope', link: 'mailto:akshat.n02@gmail.com'}
# Customize site text
pagination:
  next_page: ''
  previous_page: ''
sharing_button_prompt: ''
related_posts: ''
post_date_prefix: ''
